apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
  - image: simplyman/healthcheck
    name: kubia
    livenessProbe:                 - провірка живучості яка виконує HTTP GET 
      httpGet:
        path: /                    - шлях запиту в HTTP GET
        port: 8080                 - порт куди перевірка має підключатись

