apiVersion: batch/v1                  - Версія АПІ
kind: Job                             - тип ресурсу
metadata:
  name: batch-job                     - назва ресурсу
spec:
# completions: 5                      - якщо потрібно виконати певну к-ть(5) модулів, буде запущено один за одним 5 модуів.
# parallelism: 2                      - паралельно одночасно можуть запускатись 2 модулі
# activeDeadlineSeconds: 180          - викорустовувати в разі якщо контейнер може зависнути, видалится автоматично через 180 секунд
  template:
    metadata:
      labels:
        app: batch-job                - мітка модуля 
------------------------------------
    spec:                          |
      restartPolicy: OnFailure     |  - перезапустити виконання у разі невдалого завершення. Never - не перезапускати конейтер не залежно від результату
      containers:                  |  - шаблон модуля одноразової джоби  
      - name: main                 |
        image: simplyman/job       |
-----------------------------------
