apiVersion: v1                 - версія АПІ
kind: Pod                      - тип ресурсу
metadata:
  name: kubia-manual           - назва поду(модуля)
  labels:
    app: front/backend/etc     - мітка(для сервісів/ReplicaSet/etc) 
spec:                          - специфікація
  containers:                  - тип контейнер
  - image: simplyman/kubia     - образ контейнера
    name: kubia-kubia          - назва контейнера
    ports:
    - containerPort: 8080      - порт
      protocol: TCP            - протокол
